### ISSUE TITLE
Use publix api

### ISSUE THREAD

**Issue by zenith110** [zenith110/pubsub_api#2]
Uses publix official api opposed to web scraping

**Comment by i7solar** [comment]
**Currently:**
The current implementation of the Publix API uses Selenium which uses WebKit/WebDriver to open a Google Chrome window statically to browse around a page or perform automation. However, the dependency of JS rendering and visiting the webpage consolidates a ton of speed in this system operation. This causes more consumption of resources and also gives prone errors such as handling for XPATH's on each page statically that can change during any time.

**Future:**
The future of the implementation is that the Publix API will utilize a requests format rather than using Chrome.  The requests package will power the program in future system operation. This will allow faster speeds since we will not be rendering any JS, only communicating to the API or any HTML product-pages to scrape information on the fly.  This will cause less consumption of resources and less errors due to handling for only status codes and API errors given from Publix. (400 ,403, etc.)

**Comment by i7solar** [comment]
A final draft of the new implementation.

`
def find_closest_publix(zipcode):
    # Make a request to the publix servics endpoint to get the closest location
    response = requests.request("GET", "https://services.publix.com/api/v1/storelocation", data="", headers={}, params={"types":"R,G,H,N,S","option":"","count":"15","includeOpenAndCloseDates":"true","isWebsite":"true","zipCode":zipCode})    
    
    if response.status_code != 200:
        raise ValueError('excepted 200 status for finding closest publix, was given ' + str(response.status_code) + ' for zip: ' + zipcode)

    for store_value in response.json()["Stores"]:
        return [shave_zeros(store_value["KEY"]), store_value["NAME"]] # after the first iteration, return


def grab_end_date(product_id, publix_collection):
    # create the store cookie sub value using the store name
    store_cookie = store_to_cookie(publix_collection[1])

    headers = {
    'Cookie': 'Store={%22StoreName%22:%22' + store_cookie + '%22%2C%22StoreNumber%22:' + str(publix_collection[0]) + '%2C%22Option%22:%22ACDFJNORTUV%22%2C%22ShortStoreName%22:%22' + store_cookie + '%22}'    
    }

    response = requests.request("GET", "https://www.publix.com/pd/" + str(product_id), headers=headers, data={})
    if response.status_code != 200:
        raise ValueError('excepted 200 status for grabbing product page, was given ' + str(response.status_code) + ' for product id: ' + product_id)
         
    regex = r":&amp;quot;Valid Through [\w\s]+"
    for matchNum, match in enumerate(re.finditer(r":&amp;quot;Valid Through [\w\s]+", response.text, re.MULTILINE), start=0):
        return match.group()


def parse_publix_deli_page(zipcode):

    try:
        closest_publix = find_closest_publix(zipcode)
        print("Store found: " + closest_publix[1])
    except:
        print("an unexpected exception occured grabbing the closest publix at: " + zipcode)

    response = requests.request("GET", "https://services.publix.com/api/v3/product/SearchMultiCategory?" +
    "storeNumber=" + closest_publix[0] + "&sort=popularityrank+asc,+titlecopy+asc&rowCount=60&orderAheadOnly=true&facet=onsalemsg::On+Sale&categoryIdList=d3a5f2da-3002-4c6d-949c-db5304577efb", data="", headers={}, params={})

    
    sub_dict = []    
    # find product valid thru date
    for product in response.json()[0]:
        if "Sub" in product["title"]: # find subs only
            
            temp_dict = []

            try:
                end_date = grab_end_date(product["Productid"], closest_publix)
            except:
                print("an unexpected exception occured grabbing the end date of sub: " + product["title"])

            temp_dict.append(product["title"])      
            temp_dict.append(str(product["savingmsg"]))
            try:
                temp_dict.append(str(end_date).split("&amp;quot;Valid Through")[1].strip())
            except:
                print("an unexpected exception occured appending the valid through (end date) to: " + product["title"])


            sub_dict.append(temp_dict)

    return sub_dict


def shave_zeros(raw_store):
    store_id = ""
    for char in raw_store:
        if char != "0":
            store_id += str(char)

    return store_id

def store_to_cookie(store):
    return str(store).replace(" ", "%20")

if __name__ == "__main__":
    scrape_publix_job()
`

**Comment by i7solar** [comment]
A final draft of the new implementation using Requests.

```
def scrape_publix_job():
    '''
    Leave these alone for now, I will not be in charge of the S3 bucket / DB.
    s3 = boto3.resource(
        service_name="s3",
        region_name="us-east-2",
        aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    )
   
    bucket_name = os.getenv("BUCKET_NAME")
    my_bucket = s3.Bucket(bucket_name)

    db_object = DatabaseObject()
    db_object.user = os.getenv("USERNAME_DB")
    db_object.password = os.getenv("PASSWORD")
    db_object.host = os.getenv("HOST")
    db_object.port = os.getenv("PORT")
    db_object.database = os.getenv("DATABASE")
    db_object.table = os.getenv("TABLE")
    '''

    sub_sale_list = parse_publix_deli_page("33138")
    print(sub_sale_list)


def find_closest_publix(zipCode):
    # Make a request to the publix servics endpoint to get the closest location
    response = requests.request("GET", "https://services.publix.com/api/v1/storelocation", data="", headers={}, params={"types":"R,G,H,N,S","option":"","count":"15","includeOpenAndCloseDates":"true","isWebsite":"true","zipCode":zipCode})    
    
    if response.status_code != 200:
        raise ValueError('excepted 200 status for finding closest publix, was given ' + str(response.status_code) + ' for zip: ' + zipCode)

    for store_value in response.json()["Stores"]:
        return [shave_zeros(store_value["KEY"]), store_value["NAME"]] # after the first iteration, return


def grab_end_date(product_id, publix_collection):
    # create the store cookie sub value using the store name
    store_cookie = store_to_cookie(publix_collection[1])

    headers = {
    'Cookie': 'Store={%22StoreName%22:%22' + store_cookie + '%22%2C%22StoreNumber%22:' + str(publix_collection[0]) + '%2C%22Option%22:%22ACDFJNORTUV%22%2C%22ShortStoreName%22:%22' + store_cookie + '%22}'    
    }

    response = requests.request("GET", "https://www.publix.com/pd/" + str(product_id), headers=headers, data={})
    if response.status_code != 200:
        raise ValueError('excepted 200 status for grabbing product page, was given ' + str(response.status_code) + ' for product id: ' + product_id)
         
    regex = r":&amp;quot;Valid Through [\w\s]+"
    for matchNum, match in enumerate(re.finditer(r":&amp;quot;Valid Through [\w\s]+", response.text, re.MULTILINE), start=0):
        return match.group()


def parse_publix_deli_page(zipCode):

    try:
        closest_publix = find_closest_publix(zipCode)
        print("Store found: " + closest_publix[1])
    except:
        print("an unexpected exception occured grabbing the closest publix at: " + zipCode)

    response = requests.request("GET", "https://services.publix.com/api/v3/product/SearchMultiCategory?" +
    "storeNumber=" + closest_publix[0] + "&sort=popularityrank+asc,+titlecopy+asc&rowCount=60&orderAheadOnly=true&facet=onsalemsg::On+Sale&categoryIdList=d3a5f2da-3002-4c6d-949c-db5304577efb", data="", headers={}, params={})

    
    sub_dict = []    
    # find product valid thru date
    for product in response.json()[0]:
        if "Sub" in product["title"]: # find subs only
            
            temp_dict = []

            try:
                end_date = grab_end_date(product["Productid"], closest_publix)
            except:
                print("an unexpected exception occured grabbing the end date of sub: " + product["title"])

            temp_dict.append(product["title"])      
            temp_dict.append(str(product["savingmsg"]))
            try:
                temp_dict.append(str(end_date).split("&amp;quot;Valid Through")[1].strip())
            except:
                print("an unexpected exception occured appending the valid through (end date) to: " + product["title"])


            sub_dict.append(temp_dict)

    return sub_dict


def shave_zeros(raw_store):
    store_id = ""
    for char in raw_store:
        if char != "0":
            store_id += str(char)

    return store_id

def store_to_cookie(store):
    return str(store).replace(" ", "%20")

if __name__ == "__main__":
    scrape_publix_job()
```
